package com.mozafaq.extmergesort;

/**
 * @author Mozaffar Afaque
 */
public enum InputProperty {
    MAX_RECORDS_IN_MEMORY,
    TEMPORARY_FILES_DIRECTORY,
    MAX_RECORD_IN_OUTPUT_BATCH,
    SOURCE_IO_TYPE,
    SOURCE_S3_PATH,
    SOURCE_S3_REGION,
    SOURCE_FILESYSTEM_PATH,
    SOURCE_OBJECT_NAME,
    DESTINATION_IO_TYPE,
    DESTINATION_S3_PATH,
    DESTINATION_S3_REGION,
    DESTINATION_FILESYSTEM_PATH,
    DESTINATION_OBJECT_NAME,
    CLIENT_LOGIC_PROVIDER,
}
